input:
  file:
  type:
  id_col:
  features:
    - mean radius
    - mean texture
    - mean perimeter
    - mean area
    - mean smoothness
    - mean compactness
    - mean concavity
    - mean concave points
    - mean symmetry
    - mean fractal dimension
    - radius error
    - texture error
    - perimeter error
    - area error
    - smoothness error
    - compactness error
    - concavity error
    - concave points error
    - symmetry error
    - fractal dimension error
    - worst radius
    - worst texture
    - worst perimeter
    - worst area
    - worst smoothness
    - worst compactness
    - worst concavity
    - worst concave points
    - worst symmetry
    - worst fractal dimension
  target: target
  objective: binary_classification
preprocess:
  enabled: true
  drop:
  impute:
    enabled: true
    mean:
    median:
    mode:
    constant:
      feature1: 25
      feature2: 0.3
  outliers:
    enabled: true
    zscore:
    iqr:
    bounded:
      feature1:
      feature2:
  scalers:
    enabled: true
    standard:
    minmax:
model:
  enabled: true
